using OCAP.DeploymentManager.Models;

namespace OCAP.DeploymentManager.Services;

public class EnvironmentGenerator
{
    public string GenerateEnvironmentFileContent(DeploymentConfiguration config)
    {
        if (config == null) throw new ArgumentNullException(nameof(config));

        var sb = new System.Text.StringBuilder();

        sb.AppendLine("# Generated by OCAP Deployment Manager");
        sb.AppendLine($"# Mode: {config.Mode}");
        sb.AppendLine($"# UTC: {DateTime.UtcNow:O}");
        sb.AppendLine();
        sb.AppendLine($"POSTGRES_HOST={config.PostgresHost}");
        sb.AppendLine($"POSTGRES_DB={config.PostgresDbName}");
        sb.AppendLine($"POSTGRES_USER={config.PostgresUsername}");
        sb.AppendLine($"POSTGRES_PASSWORD={config.PostgresPassword}");
        sb.AppendLine($"POSTGRES_HOST_PORT={config.PostgresPort}");
        sb.AppendLine($"JWT_SECRET_KEY={config.JwtSecretKey}");
        sb.AppendLine($"EVENTBUS_PROVIDER={config.EventBusProvider}");
        sb.AppendLine($"RABBITMQ_USER=ocap");
        sb.AppendLine($"RABBITMQ_PASSWORD=OcapRabbit2026!");
        sb.AppendLine($"STORAGE_PROVIDER=Local");
        sb.AppendLine($"EVOLUTION_API_KEY={config.EvolutionApiKey}");
        sb.AppendLine($"ASPNETCORE_ENVIRONMENT={(config.Mode == InstallationMode.LocalDevelopment ? "Development" : "Production")}");
        return sb.ToString();
    }
}
