using OCAP.DeploymentManager.Models;

namespace OCAP.DeploymentManager.Services;

public class EnvironmentGenerator
{
    public string GenerateEnvironmentFileContent(DeploymentConfiguration config)
    {
        if (config == null) throw new ArgumentNullException(nameof(config));

        EnsureSecrets(config);

        var panelUrl = config.ResolvePublicPanelUrl();
        var apiUrl = config.ResolvePublicApiUrl();
        var redirectUri = config.ResolveGoogleRedirectUri();
        var aspnetEnv = config.Mode == InstallationMode.LocalDevelopment ? "Development" : "Production";
        var provider = NormalizeAiProvider(config.AiProvider);

        var sb = new System.Text.StringBuilder();
        sb.AppendLine("# Generated by OCAP Deployment Manager / Installer");
        sb.AppendLine($"# Mode: {config.Mode}");
        sb.AppendLine($"# Target: {config.Target}");
        sb.AppendLine($"# UTC: {DateTime.UtcNow:O}");
        sb.AppendLine();

        sb.AppendLine($"DEPLOYMENT_TARGET={config.Target}");
        sb.AppendLine($"FRONTEND_HOST_PORT={config.FrontendHostPort}");
        sb.AppendLine($"API_HOST_PORT={config.ApiHostPort}");
        sb.AppendLine($"PUBLIC_API_URL={apiUrl}");
        sb.AppendLine($"PUBLIC_PANEL_URL={panelUrl}");
        sb.AppendLine();

        sb.AppendLine($"POSTGRES_HOST={config.PostgresHost}");
        sb.AppendLine($"POSTGRES_DB={config.PostgresDbName}");
        sb.AppendLine($"POSTGRES_USER={config.PostgresUsername}");
        sb.AppendLine($"POSTGRES_PASSWORD={config.PostgresPassword}");
        sb.AppendLine($"POSTGRES_HOST_PORT={config.PostgresPort}");
        sb.AppendLine();

        sb.AppendLine($"JWT_SECRET_KEY={config.JwtSecretKey}");
        sb.AppendLine($"VAULT_MASTER_KEY={config.VaultMasterKey}");
        sb.AppendLine($"EVENTBUS_PROVIDER={config.EventBusProvider}");
        sb.AppendLine($"RABBITMQ_USER={config.RabbitMqUser}");
        sb.AppendLine($"RABBITMQ_PASSWORD={config.RabbitMqPassword}");
        sb.AppendLine($"STORAGE_PROVIDER=Local");
        sb.AppendLine($"ASPNETCORE_ENVIRONMENT={aspnetEnv}");
        sb.AppendLine();

        sb.AppendLine($"BOOTSTRAP_ADMIN_EMAIL={config.BootstrapAdminEmail}");
        sb.AppendLine($"BOOTSTRAP_ADMIN_PASSWORD={config.BootstrapAdminPassword}");
        sb.AppendLine($"BOOTSTRAP_TENANT_NAME={config.BootstrapTenantName}");
        sb.AppendLine($"BOOTSTRAP_TENANT_SLUG={config.BootstrapTenantSlug}");
        sb.AppendLine();

        sb.AppendLine($"Google__ClientId={config.GoogleClientId}");
        sb.AppendLine($"Google__ClientSecret={config.GoogleClientSecret}");
        sb.AppendLine($"Google__RedirectUri={redirectUri}");
        sb.AppendLine($"Google__UseInMemory=false");
        sb.AppendLine();

        sb.AppendLine($"AiProviders__{provider}__ApiKey={config.AiApiKey}");
        sb.AppendLine($"AiProviders__{provider}__ModelName={config.AiModelName}");
        if (!string.IsNullOrWhiteSpace(config.AiBaseUrl))
            sb.AppendLine($"AiProviders__{provider}__BaseUrl={config.AiBaseUrl}");
        sb.AppendLine();

        sb.AppendLine($"Cors__AllowedOrigins__0={panelUrl}");
        sb.AppendLine($"NEXT_PUBLIC_API_URL=");
        sb.AppendLine($"API_INTERNAL_URL=http://ocap-api:5000");
        sb.AppendLine();

        sb.AppendLine($"EVOLUTION_API_KEY={config.EvolutionApiKey}");
        sb.AppendLine($"EVOLUTION_API_URL={config.EvolutionApiUrl}");
        if (config.EnableTelegram && !string.IsNullOrWhiteSpace(config.TelegramBotToken))
            sb.AppendLine($"Telegram__BotToken={config.TelegramBotToken}");

        return sb.ToString();
    }

    private static void EnsureSecrets(DeploymentConfiguration config)
    {
        if (string.IsNullOrWhiteSpace(config.JwtSecretKey) || config.JwtSecretKey.Length < 32)
            config.JwtSecretKey = Guid.NewGuid().ToString("N") + Guid.NewGuid().ToString("N");
        if (string.IsNullOrWhiteSpace(config.VaultMasterKey) || config.VaultMasterKey.Length < 32)
            config.VaultMasterKey = Guid.NewGuid().ToString("N") + Guid.NewGuid().ToString("N");
    }

    private static string NormalizeAiProvider(string? provider)
    {
        return (provider ?? "OpenAI").Trim() switch
        {
            "Gemini" => "Gemini",
            "Claude" => "Claude",
            "Ollama" => "Ollama",
            _ => "OpenAI"
        };
    }
}
