<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OCAP.Intelligence.Domain\OCAP.Intelligence.Domain.csproj" />
    <ProjectReference Include="..\OCAP.Intelligence.Abstractions\OCAP.Intelligence.Abstractions.csproj" />
    <ProjectReference Include="..\..\Prompts\OCAP.Prompts\OCAP.Prompts.csproj" />
    <ProjectReference Include="..\..\Modules\OCAP.Agents.Domain\OCAP.Agents.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\OCAP.Agents.Abstractions\OCAP.Agents.Abstractions.csproj" />
    <ProjectReference Include="..\..\Modules\OCAP.Agents.Application\OCAP.Agents.Application.csproj" />
    <ProjectReference Include="..\..\Tools\OCAP.Tools.Abstractions\OCAP.Tools.Abstractions.csproj" />
    <ProjectReference Include="..\..\Security\OCAP.Security.Abstractions\OCAP.Security.Abstractions.csproj" />
    <ProjectReference Include="..\..\Providers\OCAP.Providers.OpenAI\OCAP.Providers.OpenAI.csproj" />
    <ProjectReference Include="..\..\Providers\OCAP.Providers.Gemini\OCAP.Providers.Gemini.csproj" />
    <ProjectReference Include="..\..\Providers\OCAP.Providers.Ollama\OCAP.Providers.Ollama.csproj" />
    <ProjectReference Include="..\..\Intelligence\OCAP.Intelligence.Mock\OCAP.Intelligence.Mock.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0-preview.1.25080.5" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
